name: moshi_build
description: 'Build env.'
runs:
  using: "composite"
  steps:
  - uses: actions/setup-python@v2
    with:
      python-version: '3.10.14'
  - uses: actions/cache@v3
    id: cache
    with:
      path: env
      key: env-${{ hashFiles('moshi/pyproject.toml') }}
  - name: Install dependencies
    if: steps.cache.outputs.cache-hit != 'true'
    shell: bash
    run: |
      python3 -m venv env
      .  env/bin/activate
      python -m pip install --upgrade pip
      pip install torch==2.4.0 --index-url https://download.pytorch.org/whl/cpu
      pip install moshi==0.2.6
      pip install pre-commit
  - name: Setup env
    shell: bash
    run: |
      source  env/bin/activate
      pre-commit install
