static_dir = "./static/"
log_dir = "$HOME/tmp/tts-logs"
instance_name = "tts"
authorized_ids = ["public_token"]

[modules.tts_py]
type = "Py"
path = "/api/tts_streaming"
text_tokenizer_file = "hf://kyutai/tts-1.6b-en_fr/tokenizer_spm_8k_en_fr_audio.model"

# Batch size determines how many parallel connections can the server handle.
# Higher values mean slower inference. Adjust to your GPU memory capacity.
batch_size = 1
text_bos_token = 1

[modules.tts_py.py]
log_folder = "$HOME/tmp/moshi-server-logs"
voice_folder = "hf-snapshot://kyutai/tts-voices/**/*.safetensors"
default_voice = "unmute-prod-website/default_voice.wav"
cfg_coef = 2.0
cfg_is_no_text = true
padding_between = 1

# Number of quantization levels for the residual vector quantizer.
# Higher means better sounding audio but longer inference.
# The maximum is typically 32, reasonable values are 8-32.
n_q = 16

padding_bonus = 0
